[global/wm]
margin-top = 1
margin-bottom = 0

[colors]
include-file = ~/.cache/wal/colors-polybar

[bar/i3]
width = 100%
height = 27
radius = 0
fixed-center = false

monitor = ${env:MONITOR:}

# Using color variables instead of hex values
background = ${colors.background}
foreground = ${colors.foreground}

padding-left = 0
padding-right = 0
module-margin-left = 0
module-margin-right = 0

font-0 = TerminessNerdFont:size=12:hintstyle=hintslight;2
font-1 = TerminessNerdFont:weight=bold:size=12:hintstyle=hintslight;2

format-margin = 0

modules-left = i3 title
modules-center = 
modules-right = nowplaying cava playerctl xkeyboard alsa date cpu memory pulseaudio 
wm-restack = i3
override-redirect = false

;; i3 workspace module
[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false
strip-wsnumbers = false
enable-click = true
enable-scroll = true
reverse-scroll = false
fuzzy-match = true

label-focused = "[%name%]"
label-focused-font = 2
label-focused-foreground = ${colors.foreground}
label-unfocused = " %name% "
label-unfocused-foreground = ${colors.background-alt}
label-visible = " %name% "
label-visible-foreground = ${colors.background-alt}
label-urgent = " %name%! "
label-urgent-foreground = ${colors.alert}

[module/title]
type = internal/xwindow
label = " %title% "
label-maxlen = 50
format-background = ${colors.primary}
format-foreground = #FFFFFF

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
label-layout = " %layout% "
format-background = ${colors.secondary}
format-foreground = #FFFFFF
label-indicator-on-capslock = "󰪛  "

[module/alsa]
type = internal/alsa

[module/date]
type = internal/date
interval = 1
date = %a %e %b, %T
label = "  %date% "
format-background = ${colors.primary}
format-foreground = #FFFFFF

[module/pulseaudio]
type = internal/pulseaudio
format-volume = "<ramp-volume><label-volume>"
label-volume = " %percentage%% "
ramp-background = ${colors.primary}

label-muted = "   muted "
label-muted-foreground = #FFFFFF
label-muted-background = ${colors.primary}
label-volume-background = ${colors.primary}
label-volume-foreground = #FFFFFF
click-right = pavucontrol

ramp-volume-0 = " 󰕿 "
ramp-volume-1 = "  "
ramp-volume-2 = "  "
ramp-volume-foreground = #FFFFFF
ramp-volume-background = ${colors.primary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "   "
;format-prefix-foreground = ${colors.primary}
label = "%percentage_used:2%% "
format-background = ${colors.primary}
format-foreground = #FFFFFF

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "  "
label = "%percentage:2%% "
format-background = ${colors.primary}
format-foreground = #FFFFFF

[module/cava]
type = custom/script
tail = true
exec = $HOME/.config/polybar/cava.sh
format = <label>
format-font = 5
label = %output%
format-foreground = #FFFFFF
interval = 1

[module/nowplaying]
type = custom/script
exec = $HOME/.config/polybar/nowplaying.sh
format = <label>
format-font = 5
label = %output%
format-foreground = #FFFFFF
interval = 1

[module/playerctl]
type = custom/text
format = <label>
label = "7\"
format-padding = 1
click-left = playerctl previous
click-middle = playerctl play-pause
click-right = playerctl next
format-foreground = #000000
format-background = #FFFFFF
